<?php

/**
 * B-C-01…C12 — the campaign endpoints.
 *
 * Every campaign this file creates is registered with `Harness::track()` and
 * hard-deleted at the end of the run. The API only ever soft-deletes, so
 * without that the fixture counts `regression.php` asserts would climb a little
 * with every run until they stopped meaning anything.
 */

declare(strict_types=1);

Harness::group('Campanii');

// --- B-C-01: creare ---------------------------------------------------------

$title = 'Campanie B-C ' . substr(Harness::uuid(), 0, 8);
$created = Harness::request('POST', '/api/v1/campaigns', Harness::campaignPayload(['title' => $title]));

Harness::same('B-C-01a', 'POST valid → 201', 201, $created['status']);

$key = (string) ($created['body']['data']['id'] ?? '');
if ($key === '') {
    Harness::check('B-C-01b', 'POST valid întoarce cheia campaniei', false, json_encode($created['body']));
    return;
}
Harness::track('campaigns', $key);
Harness::check('B-C-01b', 'POST valid întoarce cheia campaniei', true);

$list = Harness::request('GET', '/api/v1/campaigns?pageSize=200');
$titles = array_column($list['body']['data'] ?? [], 'title');
Harness::check('B-C-01c', 'campania nouă apare în listă', in_array($title, $titles, true));

// --- B-C-02: câmp obligatoriu lipsă ----------------------------------------

$before = (int) Harness::scalar('SELECT COUNT(*) FROM campaigns');

$incomplete = Harness::campaignPayload();
unset($incomplete['title']);
$rejected = Harness::request('POST', '/api/v1/campaigns', $incomplete);

Harness::same('B-C-02a', 'POST fără titlu → 422', 422, $rejected['status']);
Harness::same('B-C-02b', 'codul de eroare este VALIDATION_ERROR', 'VALIDATION_ERROR', Harness::errorCode($rejected));
Harness::same(
    'B-C-02c',
    'un POST respins nu scrie nimic',
    $before,
    (int) Harness::scalar('SELECT COUNT(*) FROM campaigns'),
);

// --- B-C-03: referințe care nu există ---------------------------------------

/*
 * The external key is generated by the server and cannot be supplied, so there
 * is no duplicate-key case to test on the way in. What a client *can* get wrong
 * is a reference to something that is not there — a parent campaign, a
 * catalogue code — and both have to be refused before anything is written.
 */
$orphan = Harness::request('POST', '/api/v1/campaigns', Harness::campaignPayload([
    'parentCampaignExternalKey' => 'camp-care-nu-exista',
]));
Harness::same('B-C-03a', 'campanie părinte inexistentă → 422', 422, $orphan['status']);

$badCatalog = Harness::request('POST', '/api/v1/campaigns', Harness::campaignPayload([
    'campaignTypeCode' => 'TIP_INEXISTENT',
]));
Harness::same('B-C-03b', 'cod de nomenclator inexistent → 422', 422, $badCatalog['status']);

$badPillar = Harness::request('POST', '/api/v1/campaigns', Harness::campaignPayload([
    'pillarCode' => 'PILON_INEXISTENT',
]));
Harness::same('B-C-03c', 'pilon inexistent → 422', 422, $badPillar['status']);

// --- B-C-04: PUT complet ----------------------------------------------------

$detail = Harness::request('GET', "/api/v1/campaigns/{$key}");
Harness::same('B-C-04a', 'GET campania nouă → 200', 200, $detail['status']);

$updated = Harness::campaignPayload([
    'title' => $title . ' (actualizat)',
    'responsible' => 'Responsabil de test',
    'tone' => 'Cald și direct',
    'products' => ['Drumeție', 'Ciclism'],
    'secondaryMessages' => ['Mesaj secundar unu', 'Mesaj secundar doi'],
    'kpiDefinitions' => [
        ['name' => 'Afișări', 'baseline' => '0', 'target' => '10000', 'source' => 'Meta'],
    ],
]);

$put = Harness::request('PUT', "/api/v1/campaigns/{$key}", $updated);
Harness::same('B-C-04b', 'PUT complet → 200', 200, $put['status']);

$row = Harness::rows(
    'SELECT title, responsible, tone, products, secondary_messages, kpi_definitions
       FROM campaigns WHERE external_key = ?',
    [$key],
)[0] ?? [];

Harness::same('B-C-04c', 'titlul s-a scris', $title . ' (actualizat)', $row['title'] ?? null);
Harness::same('B-C-04d', 'responsabilul s-a scris', 'Responsabil de test', $row['responsible'] ?? null);
Harness::same('B-C-04e', 'listele s-au scris ca JSON', ['Drumeție', 'Ciclism'], json_decode((string) ($row['products'] ?? '[]'), true));
Harness::same(
    'B-C-04f',
    'KPI-urile s-au scris',
    'Afișări',
    json_decode((string) ($row['kpi_definitions'] ?? '[]'), true)[0]['name'] ?? null,
);

// --- B-C-05…C08: concurența optimistă ---------------------------------------

$version = (int) Harness::scalar('SELECT version_number FROM campaigns WHERE external_key = ?', [$key]);

$withEtag = Harness::raw('PUT', "/api/v1/campaigns/{$key}", Harness::campaignPayload([
    'title' => $title . ' (v corectă)',
]), ['If-Match: "' . $version . '"', 'Cookie: ' . Harness::cookieFor()]);

Harness::same('B-C-05a', 'PUT cu If-Match corect → 200', 200, $withEtag['status']);
Harness::same(
    'B-C-05b',
    'version_number a crescut cu 1',
    $version + 1,
    (int) Harness::scalar('SELECT version_number FROM campaigns WHERE external_key = ?', [$key]),
);

$stale = Harness::raw('PUT', "/api/v1/campaigns/{$key}", Harness::campaignPayload([
    'title' => $title . ' (v veche)',
]), ['If-Match: "' . $version . '"', 'Cookie: ' . Harness::cookieFor()]);

Harness::same('B-C-06a', 'PUT cu If-Match vechi → 409', 409, $stale['status']);
Harness::same('B-C-06b', 'codul este STALE_VERSION', 'STALE_VERSION', Harness::errorCode($stale));

$noHeader = Harness::request('PUT', "/api/v1/campaigns/{$key}", Harness::campaignPayload([
    'title' => $title . ' (fără antet)',
]));
/*
 * Not an oversight: `If-Match` is optional by design, so a client that does not
 * send one still wins. The case is written down precisely so nobody "fixes" it
 * into a 428 and breaks every caller that never sent the header.
 */
Harness::same('B-C-07', 'PUT fără If-Match este acceptat', 200, $noHeader['status']);

$garbage = Harness::raw('PUT', "/api/v1/campaigns/{$key}", Harness::campaignPayload(), [
    'If-Match: "abc"',
    'Cookie: ' . Harness::cookieFor(),
]);
Harness::same('B-C-08', 'If-Match nevalid → 422, nu ignorat tăcut', 422, $garbage['status']);

// --- B-C-11: dependențe -----------------------------------------------------

$dependencies = Harness::request('GET', "/api/v1/campaigns/{$key}/dependencies");
Harness::same('B-C-11a', 'GET dependencies → 200', 200, $dependencies['status']);
Harness::check(
    'B-C-11b',
    'o campanie fără istoric poate fi ștearsă',
    ($dependencies['body']['data']['canDelete'] ?? null) === true,
    json_encode($dependencies['body']['data'] ?? null),
);

// --- B-C-12: export ---------------------------------------------------------

$export = Harness::request('GET', "/api/v1/campaigns/{$key}/export?visuals=link");
Harness::same('B-C-12a', 'GET export → 200', 200, $export['status']);
Harness::check(
    'B-C-12b',
    'exportul are forma unui pachet OMD',
    isset($export['body']['data']['packageType']),
    'packageType lipsește: ' . substr((string) $export['raw'], 0, 120),
);

// --- B-C-09, B-C-10: ștergere logică și revenire ----------------------------

$deleted = Harness::request('DELETE', "/api/v1/campaigns/{$key}");
Harness::same('B-C-09a', 'DELETE → 200', 200, $deleted['status']);

Harness::check(
    'B-C-09b',
    'rândul rămâne în bază, doar marcat',
    Harness::scalar('SELECT deleted_at FROM campaigns WHERE external_key = ?', [$key]) !== null,
);

$listAfter = Harness::request('GET', '/api/v1/campaigns?pageSize=200');
Harness::check(
    'B-C-09c',
    'campania ștearsă nu mai apare în listă',
    !in_array($key, array_column($listAfter['body']['data'] ?? [], 'id'), true),
);

$restored = Harness::request('POST', "/api/v1/campaigns/{$key}/restore");
Harness::same('B-C-10a', 'POST restore → 200', 200, $restored['status']);
Harness::check(
    'B-C-10b',
    'campania revine în listă',
    in_array(
        $key,
        array_column(Harness::request('GET', '/api/v1/campaigns?pageSize=200')['body']['data'] ?? [], 'id'),
        true,
    ),
);
